# Generated by Django 5.0 on 2023-12-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_network_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
