# Generated by Django 5.0 on 2023-12-27 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_network_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название организации'),
            preserve_default=False,
        ),
    ]
